### ISSUE TITLE
Update new courses

### ISSUE THREAD

**Issue by lunw1024** [AIwaffle/AIwaffle-website#3]
On top of 3 existing courses, add 3 more courses.

In this order:  
4. [Study path & Where to find resources - AIwaffle](https://www.kaggle.com/idiott/study-path-where-to-find-resources-aiwaffle) (remove "- AIwaffle" in the title)  
5. [2D point classification: Logistic Regression](https://www.kaggle.com/idiott/aiwaffle-experimental-course)  
6. [Classify handwriting digits using shallow, deep, and CNN](https://www.kaggle.com/xuyinjiesh/mnist-shallow-deep-and-cnn)  

Please contact @jimmy-zx for course links on jupyterhub. If it is impossible to determine a link, you can write a brief guide on navigating in jupyterhub.  
If the backend is not ready, just link to kaggle

Also, the current layout of AIwaffle Courses seems dull; how about trying some bold designs? (not necessary)

**Comment by lunw1024** [comment]
Lastest demand in WeChat history

**Comment by lunw1024** [comment]
Please update the courses according to AIwaffle's [course list](https://github.com/AIwaffle/AIwaffle/blob/master/Courses/course-list.md)

**Comment by AlienKevin** [comment]
I added the new courses with redirect link to kaggle and jupyterhub according to the course list. Waiting for frontend support for jupyterhub integration as per [AIwaffle_Server1#5](https://github.com/AIwaffle/AIwaffle_Server1/issues/5)

**Comment by jimmy-zx** [comment]
Links to courses are `https://www.aiwaffle.com/jhub/user/{username}/notebooks/Courses/{course_name}.ipynb`, where the `course_name` is the name of the file in `https://github.com/AIwaffle/AIwaffle/tree/master/Courses`

To get the `username`, you can use `/auth/current` [documentation](https://github.com/AIwaffle/AIwaffle_Server1/blob/dev/docs/auth.md#get-current-user)

**Comment by AlienKevin** [comment]
@jimmy-zx I tried out the oauth/create_client api's example but got a 401:
![image](https://user-images.githubusercontent.com/22850071/89727156-d2627f80-da54-11ea-9911-e1c7d04357aa.png)

![image](https://user-images.githubusercontent.com/22850071/89727166-e1e1c880-da54-11ea-964d-cdd1573f4a37.png)

Since OAuth2 is quite new to me, could you explain the logic and usage behind it?

**Comment by jimmy-zx** [comment]
This is a simple flow from the [official documentation](https://docs.authlib.org/en/latest/oauth/2/intro.html)

![OAuth2 flow](https://user-images.githubusercontent.com/290496/48670041-e5803e00-eb53-11e8-91a9-3776276d6bf6.png)

1. With a log-in session, a user could register an OAuth2 client on the authorization server ([https://aiwaffle.com/](https://aiwaffle.com/)) by accessing `/oauth/create_client` and fill in the form in the [documentation](https://github.com/AIwaffle/AIwaffle_Server1/blob/master/docs/oauth2.md#create-a-client) (Without login, the server would return 401)

2. The OAuth2 client will fill in `client_id` and `client_secret` from the `/oauth` page

3. When the user want to login, the client will generate some parameters and redirect to `/oauth/authorize` in the authorization server. After user has authorized, the user will be redirected to `redirect_uris` in the [form](https://github.com/AIwaffle/AIwaffle_Server1/blob/master/docs/oauth2.md#create-a-client).

4. At this point, the client could access everything defined in the `scope` in the [form](https://github.com/AIwaffle/AIwaffle_Server1/blob/master/docs/oauth2.md#create-a-client).

For the users, the pages they will face is the login page in the client, the authorization page (`/oauth/authorize`), and probably the 401 page (prompt for login).

Reference: [example-oauth2-server](https://github.com/authlib/example-oauth2-server/blob/master/README.md)

**Comment by AlienKevin** [comment]
@jimmy-zx Thanks for the detailed steps. After logging in I got a 400 BAD REQUEST. I'm wondering what went wrong with my request syntax? P.S. I'm using the same code as shown in the screenshots above.
